### ISSUE TITLE
Starting the default MC Docker image results in error

### ISSUE THREAD

**Issue by nfrankel** [hazelcast/management-center-docker#55]
This is the log from `hazelcast/management-center:4.2020.10`:

```
+ exec java --add-opens java.base/java.lang=ALL-UNNAMED -server -Dhazelcast.mc.home=/data -Djava.net.preferIPv4Stack=true -XX:+UseContainerSupport -XX:MaxRAMPercentage=80 -cp /opt/hazelcast/management-center/hazelcast-management-center-4.2020.10.jar -Dhazelcast.mc.contextPath=/ -Dhazelcast.mc.http.port=8080 -Dhazelcast.mc.https.port=8443 com.hazelcast.webmonitor.Launcher
using automatic sizing of heap size by up to 80% of available memory and starting with container support
##################################################
# initialisation complete, starting now....
##################################################
2020-11-18 15:07:38 [main] INFO  c.h.webmonitor.config.BuildInfo - Hazelcast Management Center 4.2020.10 (20201029 - a78b68f), Jet client version: 4.3, Hazelcast client version: 4.0.3, embedded Jetty version: 9.4.31.v20200723
2020-11-18 15:07:38 [main] WARN  o.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@3e58a80e{/,null,UNAVAILABLE,@WebApp}{file:/opt/hazelcast/management-center/hazelcast-management-center-4.2020.10.jar}
java.lang.IllegalStateException: Temp dir /tmp/jetty-0_0_0_0-8080-hazelcast-management-center-4_2020_10_jar-_-@WebApp-8354392190745654509.dir not useable: writeable=false, dir=false
	at org.eclipse.jetty.webapp.WebInfConfiguration.configureTempDirectory(WebInfConfiguration.java:547)
	at org.eclipse.jetty.webapp.WebInfConfiguration.makeTempDirectory(WebInfConfiguration.java:519)
	at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:468)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:138)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:408)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at com.hazelcast.webmonitor.Launcher.startServer(Launcher.java:138)
	at com.hazelcast.webmonitor.Launcher.start(Launcher.java:107)
	at com.hazelcast.webmonitor.Launcher.main(Launcher.java:102)
2020-11-18 15:07:38 [main] INFO  com.hazelcast.webmonitor.Launcher - 

Hazelcast Management Center successfully started at http://localhost:8080/
```

The reason is that RocksDB is not allowed to write in the `/tmp` directory. The workaround is to set the `ROCKSDB_SHAREDLIB_DIR` environment variable to a writable directory.

But the default image should not require any change.

**Comment by nfrankel** [comment]
This is the deployment file:

```yaml
apiVersion: v1
kind: Service
metadata:
  namespace: jettrain
  name: management-center
spec:
  selector:
    role: monitoring
  ports:
    - port: 8080
      nodePort: 31081
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
data:
  hazelcast-client.yaml: |-
    hazelcast-client:
      cluster-name: jet
      network:
        multicast:
          enabled: false
        kubernetes:
          enabled: true
          namespace: jettrain
          service-name: cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  namespace: jettrain
spec:
  replicas: 1
  selector:
    matchLabels:
      role: monitoring
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: monitoring
    spec:
      serviceAccountName: hazelcast-account
      containers:
        - name: monitor
          image: hazelcast/management-center:4.2020.10
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: client-config
              mountPath: /etc/client
          env:
            - name: MC_CLIENT_CONFIG
              value: /etc/client/hazelcast-client.yml
      volumes:
        - name: client-config
          configMap:
            name: client-config
```
